remove worthless complexity.

diff --git a/bin/obnam_wrapper b/bin/obnam_wrapper
--- a/bin/obnam_wrapper
+++ b/bin/obnam_wrapper
@@ -1,29 +1,30 @@
 #!/usr/bin/env bash
+#set -e
 USER=$(whoami)
 OBNAM=$(which obnam)
 LOGGER_TAG="obnam_wrapper"
 LOGGER="$(which logger) -t $LOGGER_TAG -i"
 
+echo "wtf"
 echo "starting for $USER" | $LOGGER -p user.info
 if [ -f /home/$USER/.ssh/config ] && [ -f /home/$USER/$USER.home.obnam.conf ]; then
     $OBNAM backup $HOME --config=/home/$USER/$USER.home.obnam.conf
     readonly backup_status="$?"
 else
-    echo "config test failed for $USER." | $LOGGER -p user.crit
+    echo "config for $USER not found." | $LOGGER -p user.crit
     exit 1;
 fi
+
+echo $backup_status
 
 if [ "$backup_status" = "0" ]; then
 	echo "finished for $USER." | $LOGGER -p user.info
 	exit $backup_status;
 else
 	logfile=$(awk -F "=" '/log/ {print $2; exit;}' /home/$USER/$USER.home.obnam.conf)
-    error_date=$(awk -F " " '/R681AEX/ {edate=$1}END{print edate}' $logfile)
     todayd=$(date +"%Y-%m-%d")
     hostz=$(hostname)
-    if [ "$error_date" == "$todayd" ]; then
-        echo "Obnam lock couldn't be set on $hostz" | mail -s "$todayd obnam error" $USER
-    fi
+    echo "Obnam lock couldn't be set on $hostz" | mail -s "$todayd obnam error" $USER
     echo "failed for $USER with exit status $backup_status" | $LOGGER -p user.err
     exit $backup_status;
 fi
